import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Landing from '../components/Landing'
import React, { useEffect, useState } from "react";

export default function Home() {

  return (
    <>
      <Head>
        <title>Tech Exam</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
          <Landing/>
      </main>
    </>
  )
}
